FROM {{ image_spec("openstack-base") }}
MAINTAINER {{ maintainer }}

RUN apt-get update \
    && apt-get install --no-install-recommends -q -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \
        apache2 \
        libapache2-mod-wsgi \
    && echo > /etc/apache2/ports.conf \
    && ln -s ../mods-available/headers.load /etc/apache2/mods-enabled/headers.load

{{ copy_sources("openstack/horizon", "/horizon") }}
{{ copy_sources("openstack/sahara-dashboard", "/sahara-dashboard") }}
{{ copy_sources("openstack/murano-dashboard", "/murano-dashboard") }}
{{ copy_sources("openstack/searchlight-ui", "/searchlight-ui") }}
{{ copy_sources("openstack/designate-dashboard", "/designate-dashboard") }}

RUN mkdir -p /etc/openstack-dashboard /home/horizon /var/www/cgi-bin/horizon /var/lib/microservices/venv/lib/python2.7/site-packages/openstack_dashboard/local/local_settings.d \
             /var/lib/microservices/venv/lib/python2.7/site-packages/openstack_dashboard/conf \
    && cp -a /sahara-dashboard/sahara_dashboard/enabled/* /horizon/openstack_dashboard/local/enabled/ \
    && cp -a /designate-dashboard/designatedashboard/enabled/_1710_project_dns_panel_group.py /horizon/openstack_dashboard/local/enabled/ \
    && cp -a /designate-dashboard/designatedashboard/enabled/_1720_project_dns_panel.py /horizon/openstack_dashboard/local/enabled/ \
    && cp -a /searchlight-ui/searchlight_ui/enabled/_1001_project_search_panel.py /horizon/openstack_dashboard/local/enabled/ \
    && (if [ -d /murano-dashboard/muranodashboard/conf ]; then \
       cp -r /murano-dashboard/muranodashboard/conf/* /var/lib/microservices/venv/lib/python2.7/site-packages/openstack_dashboard/conf/; fi) \
    && (if [ -d /murano-dashboard/muranodashboard/local/enabled ]; then \
        cp -a /murano-dashboard/muranodashboard/local/enabled/* /horizon/openstack_dashboard/local/enabled/; else \
        cp /murano-dashboard/muranodashboard/local/_50_murano.py /horizon/openstack_dashboard/local/enabled/;  fi) \
    && (if [ -d /murano-dashboard/muranodashboard/local/local_settings.d ]; then \
       cp -a /murano-dashboard/muranodashboard/local/local_settings.d/* /var/lib/microservices/venv/lib/python2.7/site-packages/openstack_dashboard/local/local_settings.d/ \
       && sed -i "s/^SESSION_ENGINE = .*/SESSION_ENGINE = 'django.contrib.sessions.backends.cache'/g" \
          /var/lib/microservices/venv/lib/python2.7/site-packages/openstack_dashboard/local/local_settings.d/_50_murano.py; fi) \
    && (if [ -f /searchlight-ui/searchlight_ui/conf/searchlight_policy.json ]; then \
        cp -a /searchlight-ui/searchlight_ui/conf/searchlight_policy.json /var/lib/microservices/venv/lib/python2.7/site-packages/openstack_dashboard/conf/; fi) \
    && (if [ -f /searchlight-ui/searchlight_ui/local_settings.d/_1001_search_settings.py ]; then \
        cp -a /searchlight-ui/searchlight_ui/local_settings.d/_1001_search_settings.py /var/lib/microservices/venv/lib/python2.7/site-packages/openstack_dashboard/local/local_settings.d/; fi) \
    && /var/lib/microservices/venv/bin/pip install --upgrade /horizon /sahara-dashboard /murano-dashboard /searchlight-ui /designate-dashboard \
    && useradd --user-group horizon \
    && ln -s /etc/openstack-dashboard/local_settings /var/lib/microservices/venv/lib/python2.7/site-packages/openstack_dashboard/local/local_settings.py \
    && cp -r /horizon/openstack_dashboard/conf/* /etc/openstack-dashboard/ \
    && cp /horizon/manage.py /var/lib/microservices/venv/bin/manage.py \
    && /var/lib/microservices/venv/bin/python /var/lib/microservices/venv/bin/manage.py collectstatic --noinput --clear \
    && chown -R horizon: /etc/openstack-dashboard /home/horizon /var/lib/microservices/venv/lib/python2.7/site-packages/static /horizon

ENV PATH /var/lib/venv/bin:$PATH

# Workaround for https://bugs.launchpad.net/osprofiler/+bug/1361235
RUN sed -i "s#'../..'#os.path.realpath('../..')#" /var/lib/microservices/venv/lib/python2.7/site-packages/openstack_dashboard/wsgi/django.wsgi

COPY daemon.sh /usr/local/bin/daemon.sh
COPY horizon_sudoers /etc/sudoers.d/horizon_sudoers
RUN chmod 755 /usr/local/bin/daemon.sh \
    && chmod 440 /etc/sudoers.d/horizon_sudoers
